-- app/queries/prestadores.sql
SELECT 
  RP.NOMECOMPLETO,
  RP.cpf,
  RU.DESCRICAO40 AS UNIDADE,
  E.DESCRICAO20 AS EMPRESA,
  R.SALARIOCONTRATUAL, -- Coluna que adicionamos
  RS.DESCRICAO40 AS SETOR,
  F.DESCRICAO40 AS FUNCAO,
  RB.DESCRICAO20 as ESTABELECIMENTO,
  R.ESTABELECIMENTOCONTRATA,
  case  
    when rp.cpf = '61946966304' then 'Sala CRM'
    else 
    RCC.DESCRICAO40 end  CLASSIFICACAO_CONTABIL,
    r.dataadmissao AS "DATAADMISSAO",
  rp.emailcorporativo as email_colaborador

FROM RHMETA.RHCONTRATOS R
JOIN RHMETA.RHPESSOAS RP ON R.PESSOA = RP.PESSOA AND R.EMPRESA = RP.EMPRESA
JOIN RHMETA.RHUNIDADES RU ON R.UNIDADE = RU.UNIDADE
JOIN RHMETA.RHEMPRESAS E ON R.EMPRESA = E.EMPRESA
JOIN RHMETA.RHSETORES RS ON R.SETOR = RS.SETOR
JOIN RHMETA.RHFUNCOES F ON R.FUNCAO = F.FUNCAO
JOIN RHMETA.RHCENTROSCUSTO1 C1 ON R.CENTROCUSTO1 = C1.CENTROCUSTO1
JOIN RHMETA.RHCENTROSCUSTO2 C2 ON R.CENTROCUSTO2 = C2.CENTROCUSTO2
JOIN RHMETA.RHCENTROSCUSTO3 C3 ON R.CENTROCUSTO3 = C3.CENTROCUSTO3
JOIN RHMETA.RHCENTROSCUSTO4 C4 ON R.CENTROCUSTO4 = C4.CENTROCUSTO4
JOIN RHMETA.RHESTABELECIMENTOS RB ON R.ESTABELECIMENTO = RB.ESTABELECIMENTO
JOIN RHMETA.RHCLASSCONTABEIS RCC ON R.CLASSIFICACAOCONTABIL = RCC.CLASSIFICACAOCONTABIL

WHERE R.SITUACAO IN (1,2)
AND E.DESCRICAO20 IN ('Prestadores de servi')

UNION ALL

SELECT 
  'JULIO CESAR NUNES DE SOUSA' AS NOMECOMPLETO,
  '67214673304' AS cpf,
  'Prestadores de serviço' AS UNIDADE,
  'New House' AS EMPRESA,
  1 AS SALARIOCONTRATUAL,
  'Veículos Novos' AS SETOR,
  'Gerente comercial' AS FUNCAO,
  'New House ALD' AS ESTABELECIMENTO,
  '1104' AS ESTABELECIMENTOCONTRATA,
  'Veículos Novos' AS CLASSIFICACAO_CONTABIL,
  TO_DATE('15/04/2024', 'DD/MM/YYYY') AS "DATAADMISSAO",
  'julio.nunes@gwmnewhouse.com.br' AS email_colaborador
from dual

UNION ALL

SELECT 
  'JORGEANNE UCHOA DA SILVA MELO' AS NOMECOMPLETO,
  '65293835300' AS cpf,
  'Prestadores de serviço' AS UNIDADE,
  'New House' AS EMPRESA,
  1 AS SALARIOCONTRATUAL,
  'Veículos Novos' AS SETOR,
  'Gerente comercial' AS FUNCAO,
  'New House THE' AS ESTABELECIMENTO,
  '1102' AS ESTABELECIMENTOCONTRATA,
  'Veículos Novos' AS CLASSIFICACAO_CONTABIL,
  TO_DATE('01/02/2024', 'DD/MM/YYYY') AS "DATAADMISSAO",
  'jorgeanne.melo@newlandjlr.com.br' AS email_colaborador
from dual