SELECT 
  RP.NOMECOMPLETO,
  RP.cpf,
  RU.DESCRICAO40 AS UNIDADE,
  E.DESCRICAO20 AS EMPRESA,
  R.SALARIOCONTRATUAL, -- Coluna que adicionamos
  RS.DESCRICAO40 AS SETOR,
  F.DESCRICAO40 AS FUNCAO,
  RB.DESCRICAO20 as ESTABELECIMENTO,
  R.ESTABELECIMENTOCONTRATA,
  case  
    when rp.cpf = '61946966304' then 'Sala CRM'
    else RCC.DESCRICAO40 
  end CLASSIFICACAO_CONTABIL,
  r.dataadmissao AS "DATAADMISSAO",
  --rp.emailcorporativo 
  'kelvyn.freitas@gruponew.com' as email_colaborador

FROM RHMETA.RHCONTRATOS R
JOIN RHMETA.RHPESSOAS RP ON R.PESSOA = RP.PESSOA AND R.EMPRESA = RP.EMPRESA
JOIN RHMETA.RHUNIDADES RU ON R.UNIDADE = RU.UNIDADE
JOIN RHMETA.RHEMPRESAS E ON R.EMPRESA = E.EMPRESA
JOIN RHMETA.RHSETORES RS ON R.SETOR = RS.SETOR
JOIN RHMETA.RHFUNCOES F ON R.FUNCAO = F.FUNCAO
JOIN RHMETA.RHESTABELECIMENTOS RB ON R.ESTABELECIMENTO = RB.ESTABELECIMENTO
JOIN RHMETA.RHCLASSCONTABEIS RCC ON R.CLASSIFICACAOCONTABIL = RCC.CLASSIFICACAOCONTABIL

WHERE R.SITUACAO IN (1,2)
AND E.DESCRICAO20 IN ('Prestadores de servi')
--and R.DATAADMISSAO >= TO_DATE('01/08/2025', 'DD/MM/YYYY')
UNION ALL

SELECT 
  'JULIO CESAR NUNES DE SOUSA' AS NOMECOMPLETO,
  '67214673304' AS cpf,
  'Prestadores de serviço' AS UNIDADE,
  'New House' AS EMPRESA,
  1 AS SALARIOCONTRATUAL,
  'Veículos Novos' AS SETOR,
  'Gerente comercial' AS FUNCAO,
  'New House ALD' AS ESTABELECIMENTO,
  '1104' AS ESTABELECIMENTOCONTRATA,
  'Veículos Novos' AS CLASSIFICACAO_CONTABIL,
  TO_DATE('15/04/2024', 'DD/MM/YYYY') AS "DATAADMISSAO",
  'kelvyn.freitas@gruponew.com' as email_colaborador
from dual

UNION ALL

SELECT 
  'JORGEANNE UCHOA DA SILVA MELO' AS NOMECOMPLETO,
  '65293835300' AS cpf,
  'Prestadores de serviço' AS UNIDADE,
  'New House' AS EMPRESA,
  1 AS SALARIOCONTRATUAL,
  'Veículos Novos' AS SETOR,
  'Gerente comercial' AS FUNCAO,
  'New House THE' AS ESTABELECIMENTO,
  '1102' AS ESTABELECIMENTOCONTRATA,
  'Veículos Novos' AS CLASSIFICACAO_CONTABIL,
  TO_DATE('01/02/2024', 'DD/MM/YYYY') AS "DATAADMISSAO",
  'kelvyn.freitas@gruponew.com' as email_colaborador
from dual